services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpfinal
      MYSQL_USER: hugo
      MYSQL_PASSWORD: hugo
    ports:
      - 3306:3306
    restart: always
    volumes:
        - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: hugo
      PMA_PASSWORD: hugo
      PMA_ARBITRARY: 1
    ports:
      - 8089:80
    restart: always
  nginx1:
      image: nginx:latest
      ports:
        - 80:80
      volumes:
        - ./TP-Final-3IW-ESGI/:/var/www/html/
        - ./nginx1/default.conf:/etc/nginx/conf.d/default.conf
  nginx2:
      image: nginx:latest
      ports:
        - 81:80
      volumes:
        - ./TP-Final-3IW-ESGI-2/:/var/www/html/
        - ./nginx2/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: php
    ports:
      - 9000:9000
    volumes:
      - ./TP-Final-3IW-ESGI/:/var/www/html/
  php2:
    build: php
    ports:
      - 9001:9000
    volumes:
      - ./TP-Final-3IW-ESGI-2/:/var/www/html/
volumes:
    mysql-data: