services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpfinal
      MYSQL_USER: hugo
      MYSQL_PASSWORD: hugo
    ports:
      - 3306:3306
    restart: always
    volumes:
        - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: hugo
      PMA_PASSWORD: hugo
      PMA_ARBITRARY: 1
    ports:
      - 8089:80
    restart: always
  nginx:
      image: nginx:latest
      ports:
        - 80:80
      volumes:
        - ./TP-Final-3IW-ESGI/:/var/www/html/
volumes:
    mysql-data: